### ISSUE TITLE
看了源码有点疑问

### ISSUE THREAD

**Issue by doerme** [efoxTeam/flutter-animation-set#1]
AnimatedLogo类的 scaleX、scaleY...transY 为什么要用数组, 保存一次anim值不就可以了么？ 毕竟anim 不是数组

**Comment by AndroidHensen** [comment]
因为在一次动画中可以多次 scaleX，让他们的值互不影响

**Comment by doerme** [comment]
> 因为在一次动画中可以多次 scaleX，让他们的值互不影响

那现在是一次动画中，每种类型的transform最多4次?

**Comment by AndroidHensen** [comment]
@doerme 是的，你可以看Opacity 他就是无限次的，后续我会统一改过来，让所有支持无限次
